#!/bin/bash

while true; do
    # Display prompt
    echo "jecinta_joseph$ \c"
    
    # Read user input
    read comand
    
    # Check for end of file (Ctrl+D)
    if [ -z "$comand" ]; then
        echo "Our shell exists..."
        break
    fi
    
    # Execute comand
    if [ -x "$(comand -v $comand)" ]; then
        $comand
    else
        echo "./shell: $comand: comand not found"
    fi
done
