#!/bin/bash

while true; do
    # Display prompt
    echo "#jecinta_joseph\$ \c"

    # Read user input
    read -r comand_ln

    # Check for end of file (Ctrl+D)
    if [ -z "$comand_ln" ]; then
        echo "Our shell exists..."
        break
    fi

    # Split the comand line into comand and arguments
    comand=$(echo "$comand_ln" | awk '{print $1}')
    arguments=$(echo "$comand_ln" | awk '{$1=""; print $0}')

    # Execute comand with arguments
    if [ -x "$(comand -v "$comand")" ]; then
        "$comand" $arguments
    else
        echo "./shell: $comand: comand not found"
    fi
done
