#!/bin/bash

while true; do
    # Display prompt
    echo "jecinta_joseph$ \c"

    # Read users input
    read -r comand_ln

    # Check for end of file (Ctrl+D)
    if [ -z "$comand_ln" ]; then
        echo "Our shell exists..."
        break
    fi

    # Split the comand line into comand and arguments
    comand=$(echo "$comand_ln" | awk '{print $1}')
    arguments=$(echo "$comand_ln" | awk '{$1=""; print $0}')

    # Check if the comand exists in the PATH
    if comand -v "$comand" > /dev/null 2>&1; then
        # Execute comand with arguments
        "$comand" $arguments
    else
        echo "$comand: command not found"
    fi
done
